services:
  database:
    image: postgres:15
    container_name: database
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - backend

  testredis:
    image: redis:alpine
    container_name: testredis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  python-fastapi-app:
    container_name: python_fastapi_app
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - testredis
      - database
    restart: always
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
  redis_data:
